Update to Pac4J v6 (#49)
pac4j/spring-webflux-pac4j pull request #50
Opened 2023-06-15 10:13 UTC by JapuDCret

Resolves #49.

Notes
* Adapted to the new interfaces
* Added Lombok (to make it easier to use existing classes)
* Currently untested

2023-06-16 06:34 UTC, leleuj commented
Remove the `FindBest` class and create a `org.pac4j.jee.adapter.JEEFrameworkAdapter`.

2023-06-16 20:34 UTC, JapuDCret commented
> Remove the `FindBest` class and create a `org.pac4j.jee.adapter.JEEFrameworkAdapter`.

Done, thanks for the hint!

2023-06-19 13:40 UTC, leleuj commented
Good work! See my comments to fix before the merge...

2023-06-19 14:35 UTC, leleuj requested changes

2023-06-19 14:45 UTC, JapuDCret commented on src/main/java/org/pac4j/framework/adapter/FrameworkAdapterImpl.java
> +public class FrameworkAdapterImpl extends DefaultFrameworkAdapter {
IMHO: _eww_.
To find out, that `org.pac4j.adapter.FrameworkAdapterImpl` is the requirement for the class-name was already hard for me - but now with `org.pac4j.jee.adapter.JEEFrameworkAdapter` it's also confusing for newcomers. Maybe in the future one can implement a more flexible solution like with SPIs? Or at least have a forth valid class like `org.pac4j.jee.adapter.CustomFrameworkAdapter`.

but to get back on track: Will do!

2023-06-19 15:40 UTC, leleuj commented on src/main/java/org/pac4j/framework/adapter/FrameworkAdapterImpl.java
> +public class FrameworkAdapterImpl extends DefaultFrameworkAdapter {
You're right. This is tricky. Most people won't ever know about it.

2023-06-19 15:43 UTC, leleuj requested changes

2023-06-19 15:43 UTC, leleuj commented on src/main/java/org/pac4j/springframework/web/CallbackController.java
> +            return Mono.empty();
This won't work.

Remove the `result` property from the `SpringWebfluxWebContext` and make the `SpringWebfluxHttpActionAdapter` return `response.writeWith(Mono.just(data))` or `Mono.empty();`

2023-06-19 15:43 UTC, leleuj commented on src/main/java/org/pac4j/springframework/web/CallbackController.java
> +            return Mono.empty();
3 times.

2023-06-20 08:17 UTC, leleuj approved these changes

2023-06-20 08:17 UTC, leleuj commented
Excellent! Merging...

2023-06-20 08:17 UTC, merged